### ISSUE TITLE
Rebuild With Newer Version of Go

### ISSUE THREAD

**Issue by oliverisaac** [noqcks/gucci#18]
Go 1.11 added variable re-assignment in templates. As seen in line 8 of the below example, we can append to the list and then use the list outside the `range`.

The current version produces an error like this: `Error parsing template(s): template: tmp.dQEbEZBe9r:1: unexpected "=" in operand`

Bumping the go version used to build would fix this issue.

```shell
varfile=$( mktemp --suffix json )
echo '{ "nums": [ { "n": "1" }, { "n": "2" }, { "n": "3" } ] }' > "$varfile"

templatefile=$( mktemp )
cat > $templatefile <<'EOF'
{{- $var := list }}
{{- range .nums }}
    {{- $var = append $var .n }}
{{- end }}
{{- join "," $var }}
EOF

gucci -f "$varfile" "$templatefile"

rm "$varfile" "$templatefile"
```

**Comment by noqcks** [comment]
Should be fixed by this commit: https://github.com/noqcks/gucci/commit/d1d231c0a3845cc6beae1eca56b095258748c67b

I didn't realize that travis ci deploys the first language environment in an array if you don't specify! (In this case it was deploying using go 1.8). I modified to only deploy with go 1.12.
